# Generated by Django 2.2.4 on 2019-08-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
            ],
        ),
    ]
