# Generated by Django 2.2.4 on 2019-08-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='FirstName',
            new_name='First_Name',
        ),
    ]
