# Generated by Django 2.2.4 on 2019-08-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_auto_20190817_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
