# Generated by Django 2.2.4 on 2019-08-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_auto_20190817_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='Emailid',
            field=models.CharField(default='sharmakartik21791@gmail.com', max_length=20),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='Last_Name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
