# Generated by Django 2.2.4 on 2019-09-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0005_remove_studentdetails_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='Last_Name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
